### ISSUE TITLE
Running nml.CBPE getting typeerror

### ISSUE THREAD

**Issue by langmusi** [NannyML/nannyml#124]
I got TypeError __new__() missing 1 required positional argument: 'model_metadata' 
when running this chunk of the codes:

estimator = nml.CBPE(
    y_pred_proba='y_pred_proba',
    y_pred='y_pred',
    y_true='y',
    timestamp_column_name='timestamp',
    metrics=['roc_auc', 'f1'],
    chunk_size=5000,
    problem_type='classification_binary',
    )

nannyML version is 0.4.1

What does the error describe here? Thanks for help

**Comment by nnansters** [comment]
Hey @langmusi ,

it looks like you're getting the version of NannyML mixed up with the version of the docs: you're looking at a more recent version of the docs that no longer supports the `model_metadata` parameter.

Easy to fix! Recommended way: just update your NannyML package to the latest version (currently `v0.6.2`) by running `pip install -U nannyml` or `conda update nannyml -c conda-forge`.

Alternatively you can use the docs corresponding to your installed version: https://nannyml.readthedocs.io/en/v0.4.1/index.html

Hope that helps you out!

**Comment by nnansters** [comment]
By the way: if you got version `0.4.1` from a fresh install, it might have to do with your local environment and the libraries already installed there. Those might force conda to install an older version of NannyML because of other constraints in your environment. 

If possible try installing NannyML in a fresh environment then, or feel free to reach out for any further assistance.

**Comment by langmusi** [comment]
Oh, thanks for the detailed suggestions. I will try out to see if it is possible to update nannyML. Otherwise, I will check the docs that you provided. 

Thanks.

**Comment by langmusi** [comment]
The suggestions to solve my problem are doable.
