### ISSUE TITLE
Chunk index does not continue from reference to analysis in results and plots.

### ISSUE THREAD

**Issue by jakubnml** [NannyML/nannyml#266]
In size-based chunking chunk number is reset to 0 when analysis periods starts (it should continue from the reference period). It is both - in the results and in plot:
![image](https://user-images.githubusercontent.com/100147443/228258110-de65ebf6-5bdc-4a69-926f-4944a730ec41.png)

Surprisingly_comparison_plots_ works correctly:

![image](https://user-images.githubusercontent.com/100147443/228258374-606906b6-3715-4aaa-96e6-0bdbdcb46c66.png)

**Comment by nnansters** [comment]
I think this was done by design. We felt the chunk number made more sense within the context of either the reference dataset or the analysis dataset, but not really "combined". Both sets would've been provided separately. 

Our goal of the chunk number is to help you find rows and periods in your original datasets. Agreed, the number doesn't really help here, it's more the indexes and timestamps of the chunk that help out. 
What is the goal of having the chunk number for you?
