### ISSUE TITLE
pip installing package pulls in dev dependencies

### ISSUE THREAD

**Issue by nikml** [NannyML/nannyml#67]
* nannyml version: 0.3.1.dev 098340a5bcbcaccdf9d487b9edac50b848388c2c
* Python version: 3.10
* Operating System: Fedora

### Description

pip installing the package in a conda enviroment pulls in dev dependencies such as `Sphinx`. This should not be happening.

**Comment by nnansters** [comment]
It seems like the [extras specification](https://python-poetry.org/docs/pyproject/#extras) is only supported when using Poetry to install from the source. I'm not entirely sure of that, because inspection of the PKG-INFO and `setup.py` files after running `poetry build` seem to support this. Testing has currently proven it to work differently.

Moving to the current system of `[tool.poetry.dev-dependencies]` in the build config should result in the desired behavior. I'll try this out.
