### ISSUE TITLE
extra dependencies not being installed

### ISSUE THREAD

**Issue by rfrenoy** [NannyML/nannyml#78]
Hi!

When following the instructions and running `poetry install -E test -E doc -E dev`, extra packages such as tox are not installed. I think this is related to [closed issue 67](https://github.com/NannyML/nannyml/issues/67).

This is related to [this Poetry behaviour](https://stackoverflow.com/questions/60971502/python-poetry-how-to-install-optional-dependencies). Extra packages should come from `dependencies` and not `dev-dependencies`, otherwise they are not installed.

I have tried to move the `dev-dependencies` packages within the `dependencies` section in `pyproject.toml` and after having updated the `poetry.lock` it works fine.

Do you want me to send a PR with this? I you think it would be better to somewhat separate "dev" dependencies from other dependencies, an option would be to use [Poetry dependency groups](https://python-poetry.org/docs/master/managing-dependencies/#dependency-groups) with something such as a `[tool.poetry.group.test.dependencies]` section. I can do that in the PR if you think it is better.

**Comment by nnansters** [comment]
Hi Rémy,

thanks for taking the time to experiment with NannyML and help us improve!

Just setting a quick bit of context here: the reason why we moved stuff from `dependencies` to `dev-dependencies` is to make sure they are not included in the packages being built by poetry, as they are not required for running NannyML, only for development, testing or documentation tasks.

The link you've given to the dependency groups are pointing to the `master` version of poetry, i.e. a not-yet-official release. We've decided to stick with the latest officially released version (should be `1.1.13`) so we don't force people to have to use preview releases. I'm guessing that you're running one of the `1.2.*` versions? They have a different syntax for both defining the _Poetry dependency groups_ and installing _extra dependencies_ compared to the latest release version. I'm guessing that's why the `poetry install -E test -E doc -E dev` command doesn't work as expected. 

I gave this a quick try yesterday on `1.1.13` and it seemed to work as expected.

Could you quickly confirm your poetry version? You can check by running `poetry --version`.

Cheers!

**Comment by rfrenoy** [comment]
I was using poetry `1.1.11`.

I believe the _dependency groups_ are only available on later versions of poetry (>=1.2, to be checked), however the _extras_ not being installed when specified in _dev-dependencies_ seem to be a common behaviour in all versions. I will check on 1.1.13 and come back to you.

If your intent is to avoid packages being included on built packages, isn't the _optional_ option specified in `pyproject.toml` enough, no matter if the package is specified in `dependencies` or `dev-dependencies`?

**Comment by nnansters** [comment]
Okay, I did some quick experiments and I think that I can simplify the setup as follows:

- Remove the _dependency groups_ for now (until they become properly available on the new release). Use cases right are are just "build the package" vs. "do development on the package", which means `dependencies` vs. `dev-dependencies` should cover those cases right now.

- Remove the `optional = true` setting from all `dev-dependencies`, since this is actually not correct in a `dev-dependencies` context (the official Poetry docs are not very clear about this one). By listing packages under the `dev-dependencies` they will be included by default when installing using poetry (unless providing the `--no-dev` option). They are however **not** included when building the package, which is exactly the behavior we require.

This means the `pyproject.toml` dependencies look like this:

```toml
[tool.poetry.dependencies]
python = ">=3.7.1,<3.11>"
# ...
seaborn = "^0.11.2"


[tool.poetry.dev-dependencies]
black  = "^22.3.0"
# ...
sphinx-copybutton = "^0.5.0"
```
Installation of the dependencies is now just `poetry install` and that's it.

What do you think?

**Comment by rfrenoy** [comment]
It looks fine to me! 👍

**Comment by nnansters** [comment]
Excellent, glad we got this cleaned up! Would you like to contribute this?

**Comment by rfrenoy** [comment]
Sure, I will propose a PR soon.
